---
name: build
'on': [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  mingw:
    strategy:
      fail-fast: false
      matrix:
        arch: ['32', '64']
    name: mingw${{ matrix.arch }}
    runs-on: ubuntu-latest
    container: lmmsci/linux.mingw${{ matrix.arch }}:18.04
    env:
      CMAKE_OPTS: >-
        -DUSE_WERROR=ON
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
        -DUSE_COMPILE_CACHE=ON
      CCACHE_MAXSIZE: 0
      CCACHE_NOCOMPRESS: 1
      MAKEFLAGS: -j2
    steps:
      - name: Update and configure Git
        run: |
          add-apt-repository ppa:git-core/ppa
          apt-get update
          apt-get --yes install git
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Cache ccache data
        uses: actions/cache@v3
        with:
          key: "ccache-${{ github.job }}-${{ matrix.arch }}-${{ github.ref }}\
            -${{ github.run_id }}"
          restore-keys: |
            ccache-${{ github.job }}-${{ matrix.arch }}-${{ github.ref }}-
            ccache-${{ github.job }}-${{ matrix.arch }}-
          path: ~/.ccache
      - name: Configure
        run: |
          ccache --zero-stats
          mkdir build && cd build
          ../cmake/build_win${{ matrix.arch }}.sh
      - name: Build
        run: cmake --build build
      - name: Package
        run: cmake --build build --target package
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mingw${{ matrix.arch }}
          path: build/lmms-*.exe
      - name: Trim ccache and print statistics
        run: |
          ccache --cleanup
          echo "[ccache config]"
          ccache --print-config
          echo "[ccache stats]"
          ccache --show-stats
        env:
          CCACHE_MAXSIZE: 500M
